name: Pragma Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download Pragma
      run: |
        curl -LO https://github.com/Silverlan/pragma/releases/download/nightly/pragma.zip
        unzip pragma.zip
        rm pragma.zip
      shell: bash

    - name: Create Lua Test File
      run: |
        echo 'print("Test")\nconsole.run("exit")' > lua/test.lua
      shell: bash

    - name: Run Pragma Server
      run: |
        chmod +x pragma_server.exe
        cmd /c start /B pragma_server.exe +map "test_physics" +"lua_exec test.lua"
        echo "Check..."
        # Sleep for a few seconds to give the server time to start
        sleep 5
        
        # Monitor the process by its name
        while tasklist /FI "IMAGENAME eq pragma_server.exe" 2>NUL | find /I /N "pragma_server.exe">NUL
        do
          # Sleep for a few seconds and continue monitoring
          echo "..."
          sleep 5
        done
        echo "Done"

        # Get the exit code of the process
        $exitCode = $LASTEXITCODE
        echo "Pragma Server exited with code $exitCode"
        # You can use the exit code as needed
      shell: bash
