name: Pragma Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Generate File List
      shell: bash
      run: |
        curDir=$(pwd)
        
        # Check if pragma/install directory exists
        # Generate a tree structure of the directory and save it to a text file
        cd /
        tree --dirsfirst > "$curDir/sometextfile.txt"
        
        # Move back to the original directory
        cd "$curDir"
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: CMakeCache
        path: "sometextfile.txt"
        overwrite: true
