name: Pragma Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download Pragma
      run: |
        curl -LO https://github.com/Silverlan/pragma/releases/download/nightly/pragma.zip
        unzip pragma.zip
        rm pragma.zip
      shell: bash

    - name: Create Lua Test File
      run: |
        echo 'print("Test")\nconsole.run("exit")' > lua/test.lua
      shell: bash

    - uses: mxschmitt/action-tmate@v3.14
      name: CI
