name: GameNetworkingSockets Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
    - name: Generate File List
      shell: bash
      run: |
        git clone https://github.com/ValveSoftware/GameNetworkingSockets.git
        cd GameNetworkingSockets
        git reset --hard 505c697d0abef5da2ff3be35aa4ea3687597c3e9
        sudo apt install libssl-dev
        sudo apt install libprotobuf-dev protobuf-compiler
        sudo apt-get install -y ninja-build
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        
        echo "ALL FILES:"
        ls -R
        
        curDir=$(pwd)
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: CMakeCache
        path: "sometextfile.txt"
        overwrite: true
