name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing depot_tools
      shell: bash
      run: |
        curDir=$(pwd)
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
        setx path "%path%;C:\path\to\depot_tools"
        
    - name: Initial Checkout
      shell: bash
      run: |
        mkdir crashpad
        cd crashpad
        ../depot_tools/fetch crashpad
        
    - name: Generating Build Configuration
      shell: bash
      run: |
        ./depot_tools/gn gen out/Default

    - name: Building with Ninja
      shell: bash
      run: |
        ninja -C out/Default
    
