name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
        echo "${{github.workspace}}/depot_tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Initial Checkout
      run: |
        mkdir crashpad
        cd crashpad
        fetch crashpad
        
    - name: Generating Build Configuration
      run: |
        cd crashpad/crashpad
        gn gen out/Default

    - name: Building with Ninja
      run: |
        cd crashpad/crashpad
        ninja -C out/Default
    
