name: Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing depot_tools
      shell: bash
      run: |
        curDir=$(pwd)
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH
        
    - name: Initial Checkout
      shell: bash
      run: |
        mkdir crashpad
        cd crashpad
        fetch crashpad
        
    - name: Generating Build Configuration
      shell: bash
      run: |
        cd crashpad/crashpad
        gn gen out/Default

    - name: Building with Ninja
      shell: bash
      run: |
        cd crashpad/crashpad
        ninja -C out/Default
    
