name: Pragma Workflow

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Build Crashpad
      shell: bash
      run: |
        curDir=$(pwd)
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
        setx path "%path%;C:\path\to\depot_tools"

        mkdir crashpad
        cd crashpad
        $curDir/depot_tools/fetch crashpad

        $curDir/depot_tools/gn gen out/Default

        ninja -C out/Default
    
