name: LPython

on: [push]

concurrency:
  group: environment-py-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install curl headers using Python
      shell: python
      run: |
        import subprocess
        subprocess.run(["sudo", "apt-get", "install", "libcurl4-gnutls-dev"])

        import subprocess
        import os
        curDir = os.getcwd()
        subprocess.run(["git", "clone", "https://chromium.googlesource.com/chromium/tools/depot_tools.git"])
        os.environ["PATH"] = f"{curDir}/depot_tools:{os.environ['PATH']}"
        subprocess.run(["echo", f"export PATH={curDir}/depot_tools:$PATH", ">>", "~/.bashrc"])
        os.chdir(curDir)

        import subprocess
        import os
        subprocess.run(["echo", f"{curDir}/depot_tools", ">>", "$GITHUB_PATH"])
        os.chdir(curDir)

        import subprocess
        import os
        subprocess.run(["mkdir", "crashpad"])
        os.chdir("crashpad")
        subprocess.run(["fetch", "crashpad"])
        os.chdir(curDir)

        import subprocess
        subprocess.run(["cd", "crashpad/crashpad"])
        subprocess.run(["gn", "gen", "out/Default"])
        os.chdir(curDir)

        import subprocess
        subprocess.run(["cd", "crashpad/crashpad"])
        subprocess.run(["ninja", "-C", "out/Default"])
        os.chdir(curDir)
