name: Linux Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install curl headers using Python
      shell: python
      run: |
        import subprocess
        subprocess.run(["sudo", "apt-get", "install", "libcurl4-gnutls-dev"])
      
    - name: Installing depot_tools using Python
      shell: python
      run: |
        import subprocess
        curDir = subprocess.run(["pwd"], capture_output=True, text=True).stdout.strip()
        subprocess.run(["git", "clone", "https://chromium.googlesource.com/chromium/tools/depot_tools.git"])
        subprocess.run(["echo", f"export PATH={curDir}/depot_tools:$PATH", ">>", "~/.bashrc"])

    - name: Add depot_tools to PATH using Python
      shell: python
      run: |
        import subprocess
        curDir = subprocess.run(["pwd"], capture_output=True, text=True).stdout.strip()
        subprocess.run(["echo", f"{curDir}/depot_tools", ">>", "$GITHUB_PATH"])
        
    - name: Initial Checkout using Python
      shell: python
      run: |
        import subprocess
        subprocess.run(["mkdir", "crashpad"])
        subprocess.run(["cd", "crashpad"])
        subprocess.run(["fetch", "crashpad"])
        
    - name: Generating Build Configuration using Python
      shell: python
      run: |
        import subprocess
        subprocess.run(["cd", "crashpad/crashpad"])
        subprocess.run(["gn", "gen", "out/Default"])

    - name: Building with Ninja using Python
      shell: python
      run: |
        import subprocess
        subprocess.run(["cd", "crashpad/crashpad"])
        subprocess.run(["ninja", "-C", "out/Default"])
