name: Linux

on: [push]

concurrency:
  group: environment-lin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install curl headers
      shell: bash
      run: |
        sudo apt-get install libcurl4-gnutls-dev
      
        
    - name: Installing depot_tools
      shell: bash
      run: |
        curDir=$(pwd)
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git 
        sudo echo "export PATH=$curDir/depot_tools:$PATH" >> ~/.bashrc

    - name: Add depot_tools to PATH
      shell: bash
      run: |
        echo "$(pwd)/depot_tools" >> $GITHUB_PATH
        
    - name: Initial Checkout
      shell: bash
      run: |
        mkdir crashpad
        cd crashpad
        fetch crashpad
        
    - name: Generating Build Configuration
      shell: bash
      run: |
        cd crashpad/crashpad
        gn gen out/Default

    - name: Building with Ninja
      shell: bash
      run: |
        cd crashpad/crashpad
        ninja -C out/Default
